import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { fileURLToPath } from 'node:url';
import sveltePlugin from 'esbuild-svelte';
import { writeBundleReport } from './scripts/baseline/bundle-report.mjs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const analyze = process.argv[2] === 'analyze';
const prod = process.argv[2] === 'production' || analyze;
const sourceRoot = fileURLToPath(new URL('./src', import.meta.url));

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	alias: {
		'@': sourceRoot,
	},
	bundle: true,
	plugins: [sveltePlugin()],
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	metafile: analyze,
	write: !analyze,
});

if (prod) {
	try {
		const result = await context.rebuild();
		if (analyze) await writeBundleReport(result);
	} finally {
		await context.dispose();
	}
} else {
	await context.watch();
}
