export const CUBE_FACE_POSITION_SCALE = 0.92;
export const CUBE_FACE_COORDINATE_LIMIT = 1;
export const CUBE_FACE_PADDING = 1 - CUBE_FACE_COORDINATE_LIMIT;
export const CUBE_FACE_POINTER_LIMIT =
	CUBE_FACE_COORDINATE_LIMIT / CUBE_FACE_POSITION_SCALE;
